<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2012-09-25 11:37

$extensionPath = t3lib_extMgm::extPath('pnf_cmdapi_ttnews');
return array(
	'tx_pnfcmdapittnews_ttnews_getcategories_command' => $extensionPath . 'opendata/class.tx_pnfcmdapittnews_ttnews_getcategories_command.php',
	'tx_pnfcmdapittnews_ttnews_getnews_command' => $extensionPath . 'opendata/class.tx_pnfcmdapittnews_ttnews_getnews_command.php',
	'tx_pnfcmdapittnews_tt_news_cat_datasource' => $extensionPath . 'opendata/datasource/class.tx_pnfcmdapittnews_tt_news_cat_datasource.php',
	'tx_pnfcmdapittnews_tt_news_datasource' => $extensionPath . 'opendata/datasource/class.tx_pnfcmdapittnews_tt_news_datasource.php',
);
?>