<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2012-09-25 11:37

$extensionPath = t3lib_extMgm::extPath('pnf_cmdapi_icsfd');
return array(
	'tx_pnfcmdapiicsfd_fd_getcategories_command' => $extensionPath . 'opendata/class.tx_pnfcmdapiicsfd_fd_getcategories_command.php',
	'tx_pnfcmdapiicsfd_fd_getdirectories_command' => $extensionPath . 'opendata/class.tx_pnfcmdapiicsfd_fd_getdirectories_command.php',
	'tx_pnfcmdapiicsfd_tx_icsflexdirectory_categories_datasource' => $extensionPath . 'opendata/datasource/class.tx_pnfcmdapiicsfd_tx_icsflexdirectory_categories_datasource.php',
	'tx_pnfcmdapiicsfd_tx_icsflexdirectory_sheets_datasource' => $extensionPath . 'opendata/datasource/class.tx_pnfcmdapiicsfd_tx_icsflexdirectory_sheets_datasource.php',
);
?>